import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { useMemo, useState } from "react";
import { icons, Search, SearchX, X } from "lucide-react";
import { Badge } from "../../src/components/badge";
import { Button } from "../../src/components/button";
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "../../src/components/empty";
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput,
} from "../../src/components/input-group";
import {
  ToggleGroup,
  ToggleGroupItem,
} from "../../src/components/toggle-group";
import { Toaster } from "../../src/components/sonner";
import { toast } from "sonner";
import { iconMeta } from "./icon-meta";

/*
 * The complete lucide-react icon set, made searchable. `icons` is lucide's own
 * registry (name → component) — no deprecated aliases, no utility exports — so
 * this gallery always reflects exactly the icons the package ships. Category and
 * keyword metadata come from `icon-meta.ts`, generated by
 * `scripts/vendor-icon-meta.mjs` (lucide ships the components but not their
 * metadata). Every icon inherits `currentColor`, so it picks up the active
 * theme's foreground in both light and dark mode.
 */

const meta = {
  title: "🌱 Foundations/Icons",
  parameters: { layout: "fullscreen" },
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

interface IndexedIcon {
  name: string;
  Icon: (typeof icons)[keyof typeof icons];
  categories: string[];
  /** Lowercased name + tag synonyms, for substring search. */
  haystack: string;
}

// Built once: pair each registered icon with its vendored metadata. Icons added
// to lucide-react but not yet in the metadata snapshot stay searchable by name.
const INDEX: IndexedIcon[] = Object.entries(icons).map(([name, Icon]) => {
  const m = iconMeta[name];
  return {
    name,
    Icon,
    categories: m?.categories ?? [],
    haystack: `${name} ${m?.tags.join(" ") ?? ""}`.toLowerCase(),
  };
});

// Only categories with at least one visible icon, alphabetical.
const CATEGORIES = [...new Set(INDEX.flatMap((i) => i.categories))].sort();

/**
 * Pure filter: an icon matches when its name/tags contain the (lowercased)
 * query AND — if any categories are selected — it belongs to at least one of
 * them (OR within the category facet).
 */
function filterIcons(query: string, selected: string[]): IndexedIcon[] {
  const q = query.trim().toLowerCase();
  return INDEX.filter((icon) => {
    if (q && !icon.haystack.includes(q)) return false;
    if (selected.length && !icon.categories.some((c) => selected.includes(c))) {
      return false;
    }
    return true;
  });
}

function copyImport(name: string) {
  const snippet = `import { ${name} } from "lucide-react";`;
  if (!navigator.clipboard) {
    toast.error("Clipboard unavailable", { description: snippet });
    return;
  }
  navigator.clipboard.writeText(snippet).then(
    () => toast.success(`Copied import for ${name}`, { description: snippet }),
    () => toast.error("Couldn't copy to clipboard", { description: snippet }),
  );
}

function IconGallery() {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const results = useMemo(
    () => filterIcons(query, selected),
    [query, selected],
  );
  const hasFilters = query.trim() !== "" || selected.length > 0;
  const clear = () => {
    setQuery("");
    setSelected([]);
  };

  return (
    <div className="flex flex-col gap-4">
      {/* Sticky controls so search/filters stay reachable while scrolling. */}
      <div className="bg-background/95 supports-[backdrop-filter]:bg-background/80 sticky top-0 z-10 flex flex-col gap-3 border-b py-3 backdrop-blur">
        <InputGroup>
          <InputGroupAddon>
            <Search />
          </InputGroupAddon>
          <InputGroupInput
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder={`Search ${INDEX.length.toLocaleString()} icons by name or keyword…`}
            aria-label="Search icons"
          />
          {query !== "" && (
            <InputGroupAddon align="inline-end">
              <InputGroupButton
                size="icon-xs"
                onClick={() => setQuery("")}
                aria-label="Clear search"
              >
                <X />
              </InputGroupButton>
            </InputGroupAddon>
          )}
        </InputGroup>

        <ToggleGroup
          type="multiple"
          variant="outline"
          size="sm"
          spacing={1}
          value={selected}
          onValueChange={setSelected}
          aria-label="Filter by category"
          className="w-full flex-wrap justify-start"
        >
          {CATEGORIES.map((category) => (
            <ToggleGroupItem
              key={category}
              value={category}
              className="capitalize"
            >
              {category.replace(/-/g, " ")}
            </ToggleGroupItem>
          ))}
        </ToggleGroup>
      </div>

      <div className="flex items-center gap-3 text-sm">
        <Badge variant="secondary">
          {results.length.toLocaleString()}{" "}
          {results.length === 1 ? "icon" : "icons"}
          {hasFilters && " matching"}
        </Badge>
        {hasFilters && (
          <button
            type="button"
            onClick={clear}
            className="text-muted-foreground hover:text-foreground underline-offset-4 hover:underline"
          >
            Clear filters
          </button>
        )}
      </div>

      {results.length === 0 ? (
        <Empty className="border">
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <SearchX />
            </EmptyMedia>
            <EmptyTitle>No icons found</EmptyTitle>
            <EmptyDescription>
              Nothing matches your search and filters. Try a different keyword
              or clear them.
            </EmptyDescription>
          </EmptyHeader>
          <EmptyContent>
            <Button variant="outline" size="sm" onClick={clear}>
              Clear filters
            </Button>
          </EmptyContent>
        </Empty>
      ) : (
        <div className="grid grid-cols-[repeat(auto-fill,minmax(5rem,1fr))] gap-2">
          {results.map(({ name, Icon }) => (
            <button
              key={name}
              type="button"
              title={name}
              onClick={() => copyImport(name)}
              className="text-foreground hover:bg-accent hover:text-accent-foreground focus-visible:border-ring focus-visible:ring-ring/50 flex aspect-square cursor-pointer flex-col items-center justify-center gap-1.5 rounded-md border p-2 text-center transition-colors focus-visible:ring-[3px] focus-visible:outline-none"
            >
              <Icon className="size-5" aria-hidden />
              <span className="text-muted-foreground w-full truncate text-[10px] leading-tight">
                {name}
              </span>
            </button>
          ))}
        </div>
      )}

      <Toaster />
    </div>
  );
}

// Hidden from the sidebar (!dev): the visible page is Icons.mdx, which embeds
// this story via <Canvas of={...}> and stays covered by the axe gate.
export const All: Story = {
  tags: ["!dev"],
  render: () => <IconGallery />,
};
