import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Dashboard01 from "../../src/blocks/dashboard-01/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "🧊 Blocks/Dashboard/Dashboard 01",
  component: Dashboard01,
  parameters: { layout: "fullscreen",
    // Pristine vendored block markup trips these axe rules when rendered
    // headlessly (no layout/portals in happy-dom); see scripts/vendor-blocks.mjs.
    a11y: { disabledRules: ["button-name", "empty-table-header", "label"] }, },
} satisfies Meta<typeof Dashboard01>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
