import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Login01 from "../../src/blocks/login-01/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Authentication/Login 01",
  component: Login01,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Login01>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
