import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Login03 from "../../src/blocks/login-03/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Authentication/Login 03",
  component: Login03,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Login03>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
