import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Login04 from "../../src/blocks/login-04/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "🧊 Blocks/Authentication/Login 04",
  component: Login04,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Login04>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
