import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Login05 from "../../src/blocks/login-05/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "🧊 Blocks/Authentication/Login 05",
  component: Login05,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Login05>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
