import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Login02 from "../../src/blocks/login-02/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Authentication/Login 02",
  component: Login02,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Login02>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
