import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar04 from "../../src/blocks/sidebar-04/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Sidebar/Sidebar 04",
  component: Sidebar04,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Sidebar04>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
