import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar08 from "../../src/blocks/sidebar-08/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Sidebar/Sidebar 08",
  component: Sidebar08,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Sidebar08>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
