import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar16 from "../../src/blocks/sidebar-16/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Sidebar/Sidebar 16",
  component: Sidebar16,
  parameters: { layout: "fullscreen",
    // Pristine vendored block markup trips these axe rules when rendered
    // headlessly (no layout/portals in happy-dom); see scripts/vendor-blocks.mjs.
    a11y: { disabledRules: ["button-name"] }, },
} satisfies Meta<typeof Sidebar16>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
