import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar03 from "../../src/blocks/sidebar-03/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "🧊 Blocks/Sidebar/Sidebar 03",
  component: Sidebar03,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Sidebar03>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
