import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar13 from "../../src/blocks/sidebar-13/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Sidebar/Sidebar 13",
  component: Sidebar13,
  parameters: { layout: "fullscreen",
    // Pristine vendored block markup trips these axe rules when rendered
    // headlessly (no layout/portals in happy-dom); see scripts/vendor-blocks.mjs.
    a11y: { disabledRules: ["aria-hidden-focus"] }, },
} satisfies Meta<typeof Sidebar13>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
