import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar14 from "../../src/blocks/sidebar-14/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "🧊 Blocks/Sidebar/Sidebar 14",
  component: Sidebar14,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Sidebar14>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
