import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar12 from "../../src/blocks/sidebar-12/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Sidebar/Sidebar 12",
  component: Sidebar12,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Sidebar12>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
