import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar01 from "../../src/blocks/sidebar-01/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Sidebar/Sidebar 01",
  component: Sidebar01,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Sidebar01>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
