import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar09 from "../../src/blocks/sidebar-09/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Sidebar/Sidebar 09",
  component: Sidebar09,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Sidebar09>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
