import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar06 from "../../src/blocks/sidebar-06/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "🧊 Blocks/Sidebar/Sidebar 06",
  component: Sidebar06,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Sidebar06>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
