import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar07 from "../../src/blocks/sidebar-07/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Sidebar/Sidebar 07",
  component: Sidebar07,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Sidebar07>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
