import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar02 from "../../src/blocks/sidebar-02/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "🧊 Blocks/Sidebar/Sidebar 02",
  component: Sidebar02,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Sidebar02>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
