import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Sidebar11 from "../../src/blocks/sidebar-11/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Sidebar/Sidebar 11",
  component: Sidebar11,
  parameters: { layout: "fullscreen",
    // Pristine vendored block markup trips these axe rules when rendered
    // headlessly (no layout/portals in happy-dom); see scripts/vendor-blocks.mjs.
    a11y: { disabledRules: ["list"] }, },
} satisfies Meta<typeof Sidebar11>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
