import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Signup04 from "../../src/blocks/signup-04/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "🧊 Blocks/Authentication/Sign Up 04",
  component: Signup04,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Signup04>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
