import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Signup03 from "../../src/blocks/signup-03/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "Blocks/Authentication/Sign Up 03",
  component: Signup03,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Signup03>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
