import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Signup01 from "../../src/blocks/signup-01/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "🧊 Blocks/Authentication/Sign Up 01",
  component: Signup01,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Signup01>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
