import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Signup05 from "../../src/blocks/signup-05/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "🧊 Blocks/Authentication/Sign Up 05",
  component: Signup05,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Signup05>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
