import type { Meta, StoryObj } from "@storybook/nextjs-vite";

import Signup02 from "../../src/blocks/signup-02/page";

// Vendored shadcn block — full-page composition rendered under the active
// brand × mode. Generated by scripts/vendor-blocks.mjs.
const meta = {
  title: "🧊 Blocks/Authentication/Sign Up 02",
  component: Signup02,
  parameters: { layout: "fullscreen", },
} satisfies Meta<typeof Signup02>;

export default meta;

export const Default: StoryObj<typeof meta> = {};
