/*
 * Generates the shipped token stylesheet from the typed token source — the
 * single source of truth, so the static CSS can never drift from the TS tokens.
 *
 *   :root / .dark        Mind default (base primitives + complete alias layer)
 *   @theme inline        Tailwind v4 mapping (utilities + radius scale + fonts)
 *   [data-mind-theme=…]  scoped rules for every built-in theme (both modes)
 *
 * Run via `pnpm gen:css` (and automatically before `pnpm build`).
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { themesCss } from "../src/theme/inject";
import { emitRootCss, emitThemeInline } from "../src/theme/serialize";
import { mind } from "../src/themes/mind";
import { themeList } from "../src/themes/index";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, "../styles.css");

const css = `/*
 * @mind-studio/ui — token stylesheet (GENERATED by scripts/gen-styles.ts; do not edit).
 *
 * Consumers: import this inside your Tailwind v4 entry, e.g.
 *   @import "tailwindcss";
 *   @import "@mind-studio/ui/styles.css";
 *   @source "../node_modules/@mind-studio/ui/dist";
 */

${emitRootCss(mind)}

@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--border);
  }
  *:focus-visible {
    outline-color: var(--ring);
  }
  /*
   * Typography roles (brand-agnostic; resolve through each theme's --font-*):
   *   h1–h3  display headings → the brand serif (Fraunces in Mind)
   *   h4–h6  structural headings → inherit the body sans (Hanken), legible at
   *          small sizes in dense UI
   *   code/kbd/pre/samp → the brand mono (handled by Tailwind preflight via
   *          --font-mono; <kbd> additionally fixed in its component)
   * Override per-element with the font-sans/serif/mono utilities where needed.
   */
  h1,
  h2,
  h3 {
    font-family: var(--font-serif);
  }
}

${emitThemeInline()}

${themesCss(themeList)}
`;

writeFileSync(outPath, css, "utf8");
console.log(`[gen:css] wrote ${outPath} (${css.length} bytes)`);
